/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mik.filesafe.gui;

import java.util.List;
import javax.swing.UIManager;
import mik.filesafe.entity.User;
import mik.filesafe.processor.FileProcessor;

/**
 *
 * @author Monjurul Islam Khan
 */
public class LogInForm extends javax.swing.JFrame {

    private List<User> userList;
    FileProcessor fp;

    /**
     * Creates new form LogInForm
     */
    public LogInForm() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        fp = new FileProcessor();
        
        fp.prepareSystem();
        this.userList = fp.getExistingUser();
        initComponents();
        this.lblErrorMsg.setVisible(false);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogIn = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblErrorMsg = new javax.swing.JLabel();
        lblCreateAcc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("File Savior - Log In");
        setResizable(false);

        jPanelLogIn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanelLogIn.setLayout(null);

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 204, 255));
        lblName.setText("User Name: ");
        jPanelLogIn.add(lblName);
        lblName.setBounds(60, 80, 71, 15);

        txtName.setPreferredSize(new java.awt.Dimension(10, 24));
        jPanelLogIn.add(txtName);
        txtName.setBounds(130, 76, 148, 24);

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(204, 204, 255));
        lblPassword.setText("Password: ");
        jPanelLogIn.add(lblPassword);
        lblPassword.setBounds(60, 130, 71, 15);

        jPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPassword.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPassword.setPreferredSize(new java.awt.Dimension(6, 26));
        jPanelLogIn.add(jPassword);
        jPassword.setBounds(130, 130, 150, 26);

        btnLogIn.setBackground(new java.awt.Color(95, 102, 103));
        btnLogIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogIn.setText("Sign In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        jPanelLogIn.add(btnLogIn);
        btnLogIn.setBounds(120, 180, 77, 30);

        btnCancel.setBackground(new java.awt.Color(95, 102, 103));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanelLogIn.add(btnCancel);
        btnCancel.setBounds(210, 180, 77, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Log in.");
        jPanelLogIn.add(jLabel2);
        jLabel2.setBounds(140, 10, 80, 30);

        lblErrorMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblErrorMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMsg.setText("Log in error! ");
        jPanelLogIn.add(lblErrorMsg);
        lblErrorMsg.setBounds(150, 110, 90, 14);

        lblCreateAcc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCreateAcc.setForeground(new java.awt.Color(204, 204, 255));
        lblCreateAcc.setText("Create new account.");
        lblCreateAcc.setToolTipText("Create new account");
        lblCreateAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreateAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateAccMouseClicked(evt);
            }
        });
        jPanelLogIn.add(lblCreateAcc);
        lblCreateAcc.setBounds(130, 150, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Projects\\JavaApps\\FileSavior\\resource\\login.jpg")); // NOI18N
        jPanelLogIn.add(jLabel1);
        jLabel1.setBounds(-10, -10, 350, 260);
        jLabel1.getAccessibleContext().setAccessibleParent(this);

        jMenuFile.setText("File");

        jMenuItem1.setText("Options");
        jMenuFile.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem2);

        jMenu.add(jMenuFile);

        jMenu2.setText("Edit");
        jMenu.add(jMenu2);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(376, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void setUserList(List<User> userList) {
        this.userList = userList;
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.txtName.setText("");
        this.jPassword.setText("");
        this.lblErrorMsg.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        this.userList = fp.getExistingUser();
         User userObj = new User("dummyObj", "", "");
        String userName = this.txtName.getText().toString();
        char[] pass = this.jPassword.getPassword();
        String password = String.valueOf(pass);
//        System.out.println("Log in done for " + userName + " and password is " + password);

        boolean logInSuccess = false;
        for (int i = 0; i < this.userList.size(); i++) {
            if (this.userList.get(i).getUserName().equals(userName)) {
                if (this.userList.get(i).getPassword().equals(password)) {
//                    System.out.println("Log in done");
                    userObj = userList.get(i);
                    userObj.setLastModifiedDate(fp.getCurrentTimeAsString());
                  logInSuccess = true;
                }
            }
        }
        if (logInSuccess) {
          final MainGui mainGuiObj =  new MainGui();
          mainGuiObj.setMyDetails(userObj);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            
                            mainGuiObj.setVisible(true);

                        }
                    });
        }else{
            this.lblErrorMsg.setVisible(true);
        }

    }//GEN-LAST:event_btnLogInActionPerformed

    private void lblCreateAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateAccMouseClicked
        // TODO add your handling code here:
        final CreateAccountGui createAcc = new CreateAccountGui();
        this.setFocusable(false);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                createAcc.setVisible(true);
            }
        });

    }//GEN-LAST:event_lblCreateAccMouseClicked

    // <editor-fold defaultstate="collapsed" desc="Variables declaration"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanelLogIn;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel lblCreateAcc;
    private javax.swing.JLabel lblErrorMsg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
